version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: "docker"
  directory: "/cmd/webhook"
  schedule:
    interval: weekly
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: "/"
  allow:
  - dependency-type: "all"
  schedule:
    interval: weekly
  groups:
    golang-dependencies:
      patterns:
        - "github.com/golang*"
    k8s-dependencies:
      patterns:
        - "k8s.io*"
        - "sigs.k8s.io*"
        - "github.com/kubernetes-csi*"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
    - "kind/cleanup"
  open-pull-requests-limit: 10
